import 'package:q_bank/modules/exam/exam.dart';
import 'package:q_bank/modules/home/home.dart';
import 'package:q_bank/modules/subjects/subjects.dart';

var subjectDummyData = SubjectMapper.fromJsonListToEntityList([
  {
    "id": "1",
    "name": "Mathematics",
    "exam_count": 3,
    "attempted_exam_count": 2,
  },
  {"id": "2", "name": "Physics", "exam_count": 3, "attempted_exam_count": 1},
  {"id": "3", "name": "Chemistry", "exam_count": 2, "attempted_exam_count": 1},
  {"id": "4", "name": "Biology", "exam_count": 2, "attempted_exam_count": 0},
  {"id": "5", "name": "English", "exam_count": 2, "attempted_exam_count": 2},
  {
    "id": "6",
    "name": "Computer Science",
    "exam_count": 2,
    "attempted_exam_count": 1,
  },
]);
var examDummyData = ExamMapper.fromJsonListToEntityList([
  {
    "id": "math_exam_1",
    "created_at": "2025-01-10",
    "title": "Mathematics Fundamentals Test",
    "description": "Covers arithmetic, algebra, and basic geometry.",
    "has_timer": true,
    "duration_seconds": 9,
    "questions": [
      {
        "id": "math_1_q1",
        "order_id": "1",
        "text": "What is the value of 12 × 8?",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_1_q1_o1", "text": "86", "image_url": null},
          {"id": "math_1_q1_o2", "text": "96", "image_url": null},
          {"id": "math_1_q1_o3", "text": "104", "image_url": null},
          {"id": "math_1_q1_o4", "text": "108", "image_url": null},
        ],
      },
      {
        "id": "math_1_q2",
        "order_id": "2",
        "text": "Select all prime numbers.",
        "type": "multi",
        "is_mandatory": true,
        "error_text": "Select at least one option.",
        "options": [
          {"id": "math_1_q2_o1", "text": "2", "image_url": null},
          {"id": "math_1_q2_o2", "text": "9", "image_url": null},
          {"id": "math_1_q2_o3", "text": "13", "image_url": null},
          {"id": "math_1_q2_o4", "text": "21", "image_url": null},
        ],
      },
      {
        "id": "math_1_q3",
        "order_id": "3",
        "text": "Solve for x: 3x + 5 = 20",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_1_q3_o1", "text": "3", "image_url": null},
          {"id": "math_1_q3_o2", "text": "5", "image_url": null},
          {"id": "math_1_q3_o3", "text": "7", "image_url": null},
          {"id": "math_1_q3_o4", "text": "9", "image_url": null},
        ],
      },
      {
        "id": "math_1_q4",
        "order_id": "4",
        "text": "Write the formula for the area of a rectangle.",
        "type": "text",
        "is_mandatory": false,
        "error_text": "This field is mandatory*",
        "options": [],
      },
      {
        "id": "math_1_q5",
        "order_id": "5",
        "text":
            "A triangle has angles 90°, 45°, and 45°. What type of triangle is it?",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_1_q5_o1", "text": "Scalene triangle", "image_url": null},
          {
            "id": "math_1_q5_o2",
            "text": "Right isosceles triangle",
            "image_url": null,
          },
          {
            "id": "math_1_q5_o3",
            "text": "Equilateral triangle",
            "image_url": null,
          },
          {"id": "math_1_q5_o4", "text": "Obtuse triangle", "image_url": null},
        ],
      },
    ],
  },
  {
    "id": "math_exam_2",
    "created_at": "2025-01-12",
    "title": "Algebra Practice Set",
    "description": "Focuses on linear equations and expressions.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "math_2_q1",
        "order_id": "1",
        "text": "Simplify: 2a + 3a",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_2_q1_o1", "text": "5a", "image_url": null},
          {"id": "math_2_q1_o2", "text": "6a", "image_url": null},
          {"id": "math_2_q1_o3", "text": "a5", "image_url": null},
          {"id": "math_2_q1_o4", "text": "23a", "image_url": null},
        ],
      },
      {
        "id": "math_2_q2",
        "order_id": "2",
        "text": "Which of the following are like terms?",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "math_2_q2_o1", "text": "4x and 9x", "image_url": null},
          {"id": "math_2_q2_o2", "text": "3y and 3x", "image_url": null},
          {"id": "math_2_q2_o3", "text": "7ab and 2ab", "image_url": null},
          {"id": "math_2_q2_o4", "text": "m and m²", "image_url": null},
        ],
      },
      {
        "id": "math_2_q3",
        "order_id": "3",
        "text": "If y = 2x + 1 and x = 4, what is y?",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_2_q3_o1", "text": "7", "image_url": null},
          {"id": "math_2_q3_o2", "text": "8", "image_url": null},
          {"id": "math_2_q3_o3", "text": "9", "image_url": null},
          {"id": "math_2_q3_o4", "text": "10", "image_url": null},
        ],
      },
      {
        "id": "math_2_q4",
        "order_id": "4",
        "text": "Explain in one sentence what a variable is.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "math_exam_3",
    "created_at": "2025-01-15",
    "title": "Geometry Quick Quiz",
    "description": "Tests basic properties of shapes and angles.",
    "has_timer": true,
    "duration_seconds": 1200,
    "questions": [
      {
        "id": "math_3_q1",
        "order_id": "1",
        "text": "How many sides does a hexagon have?",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "math_3_q1_o1", "text": "5", "image_url": null},
          {"id": "math_3_q1_o2", "text": "6", "image_url": null},
          {"id": "math_3_q1_o3", "text": "7", "image_url": null},
          {"id": "math_3_q1_o4", "text": "8", "image_url": null},
        ],
      },
      {
        "id": "math_3_q2",
        "order_id": "2",
        "text": "Select all quadrilaterals.",
        "type": "multi",
        "is_mandatory": true,
        "error_text": "Select at least one option.",
        "options": [
          {"id": "math_3_q2_o1", "text": "Rectangle", "image_url": null},
          {"id": "math_3_q2_o2", "text": "Triangle", "image_url": null},
          {"id": "math_3_q2_o3", "text": "Square", "image_url": null},
          {"id": "math_3_q2_o4", "text": "Circle", "image_url": null},
        ],
      },
      {
        "id": "math_3_q3",
        "order_id": "3",
        "text": "Write the sum of the angles in a triangle.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "physics_exam_1",
    "created_at": "2025-01-18",
    "title": "Physics Mechanics Test",
    "description": "Covers motion, force, and energy.",
    "has_timer": true,
    "duration_seconds": 2100,
    "questions": [
      {
        "id": "physics_1_q1",
        "order_id": "1",
        "text": "What is the SI unit of force?",
        "type": "single",
        "is_mandatory": true,
        "error_text": "Please select one answer.",
        "options": [
          {"id": "physics_1_q1_o1", "text": "Joule", "image_url": null},
          {"id": "physics_1_q1_o2", "text": "Newton", "image_url": null},
          {"id": "physics_1_q1_o3", "text": "Pascal", "image_url": null},
          {"id": "physics_1_q1_o4", "text": "Watt", "image_url": null},
        ],
      },
      {
        "id": "physics_1_q2",
        "order_id": "2",
        "text": "Select all scalar quantities.",
        "type": "multi",
        "is_mandatory": true,
        "error_text": "Select at least one option.",
        "options": [
          {"id": "physics_1_q2_o1", "text": "Speed", "image_url": null},
          {"id": "physics_1_q2_o2", "text": "Velocity", "image_url": null},
          {"id": "physics_1_q2_o3", "text": "Mass", "image_url": null},
          {"id": "physics_1_q2_o4", "text": "Acceleration", "image_url": null},
        ],
      },
      {
        "id": "physics_1_q3",
        "order_id": "3",
        "text":
            "A car moves at constant speed in a straight line. What is its acceleration?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "physics_1_q3_o1", "text": "0 m/s²", "image_url": null},
          {"id": "physics_1_q3_o2", "text": "1 m/s²", "image_url": null},
          {"id": "physics_1_q3_o3", "text": "9.8 m/s²", "image_url": null},
          {
            "id": "physics_1_q3_o4",
            "text": "Cannot be determined",
            "image_url": null,
          },
        ],
      },
      {
        "id": "physics_1_q4",
        "order_id": "4",
        "text": "Write Newton's second law in formula form.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "physics_exam_2",
    "created_at": "2025-01-20",
    "title": "Electricity Basics",
    "description": "Fundamental concepts of current, voltage, and resistance.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "physics_2_q1",
        "order_id": "1",
        "text": "What device is used to measure electric current?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "physics_2_q1_o1", "text": "Voltmeter", "image_url": null},
          {"id": "physics_2_q1_o2", "text": "Ammeter", "image_url": null},
          {"id": "physics_2_q1_o3", "text": "Barometer", "image_url": null},
          {"id": "physics_2_q1_o4", "text": "Thermometer", "image_url": null},
        ],
      },
      {
        "id": "physics_2_q2",
        "order_id": "2",
        "text": "Select all good electrical conductors.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "physics_2_q2_o1", "text": "Copper", "image_url": null},
          {"id": "physics_2_q2_o2", "text": "Rubber", "image_url": null},
          {"id": "physics_2_q2_o3", "text": "Aluminum", "image_url": null},
          {"id": "physics_2_q2_o4", "text": "Plastic", "image_url": null},
        ],
      },
      {
        "id": "physics_2_q3",
        "order_id": "3",
        "text": "State Ohm's law in words.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "physics_exam_3",
    "created_at": "2025-01-22",
    "title": "Waves and Sound Quiz",
    "description": "Basic properties of waves and sound.",
    "has_timer": true,
    "duration_seconds": 900,
    "questions": [
      {
        "id": "physics_3_q1",
        "order_id": "1",
        "text": "Which wave requires a medium to travel?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "physics_3_q1_o1", "text": "Light wave", "image_url": null},
          {"id": "physics_3_q1_o2", "text": "Radio wave", "image_url": null},
          {"id": "physics_3_q1_o3", "text": "Sound wave", "image_url": null},
          {"id": "physics_3_q1_o4", "text": "X-ray", "image_url": null},
        ],
      },
      {
        "id": "physics_3_q2",
        "order_id": "2",
        "text": "Select properties of a wave.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "physics_3_q2_o1", "text": "Amplitude", "image_url": null},
          {"id": "physics_3_q2_o2", "text": "Frequency", "image_url": null},
          {"id": "physics_3_q2_o3", "text": "Density", "image_url": null},
          {"id": "physics_3_q2_o4", "text": "Wavelength", "image_url": null},
        ],
      },
    ],
  },
  {
    "id": "chem_exam_1",
    "created_at": "2025-01-25",
    "title": "Chemistry Elements Test",
    "description": "Basic atomic structure and periodic table questions.",
    "has_timer": true,
    "duration_seconds": 1500,
    "questions": [
      {
        "id": "chem_1_q1",
        "order_id": "1",
        "text": "What is the chemical symbol for Sodium?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "chem_1_q1_o1", "text": "So", "image_url": null},
          {"id": "chem_1_q1_o2", "text": "Na", "image_url": null},
          {"id": "chem_1_q1_o3", "text": "S", "image_url": null},
          {"id": "chem_1_q1_o4", "text": "Sd", "image_url": null},
        ],
      },
      {
        "id": "chem_1_q2",
        "order_id": "2",
        "text": "Select all metals.",
        "type": "multi",
        "is_mandatory": true,
        "error_text": "Select at least one option.",
        "options": [
          {"id": "chem_1_q2_o1", "text": "Iron", "image_url": null},
          {"id": "chem_1_q2_o2", "text": "Oxygen", "image_url": null},
          {"id": "chem_1_q2_o3", "text": "Copper", "image_url": null},
          {"id": "chem_1_q2_o4", "text": "Hydrogen", "image_url": null},
        ],
      },
      {
        "id": "chem_1_q3",
        "order_id": "3",
        "text": "Write the formula for water.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "chem_exam_2",
    "created_at": "2025-01-27",
    "title": "Acids, Bases and Salts",
    "description": "Introduction to acids, bases, and indicators.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "chem_2_q1",
        "order_id": "1",
        "text": "Which of the following is an acid?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "chem_2_q1_o1", "text": "HCl", "image_url": null},
          {"id": "chem_2_q1_o2", "text": "NaOH", "image_url": null},
          {"id": "chem_2_q1_o3", "text": "KOH", "image_url": null},
          {"id": "chem_2_q1_o4", "text": "NH₄OH", "image_url": null},
        ],
      },
      {
        "id": "chem_2_q2",
        "order_id": "2",
        "text": "Select all common acid-base indicators.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "chem_2_q2_o1", "text": "Litmus", "image_url": null},
          {"id": "chem_2_q2_o2", "text": "Phenolphthalein", "image_url": null},
          {"id": "chem_2_q2_o3", "text": "Sand", "image_url": null},
          {"id": "chem_2_q2_o4", "text": "Methyl orange", "image_url": null},
        ],
      },
    ],
  },
  {
    "id": "bio_exam_1",
    "created_at": "2025-01-29",
    "title": "Biology Cell Structure Test",
    "description": "Basic cell biology and organelle functions.",
    "has_timer": true,
    "duration_seconds": 1500,
    "questions": [
      {
        "id": "bio_1_q1",
        "order_id": "1",
        "text": "What is the control center of the cell?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "bio_1_q1_o1", "text": "Nucleus", "image_url": null},
          {"id": "bio_1_q1_o2", "text": "Cytoplasm", "image_url": null},
          {"id": "bio_1_q1_o3", "text": "Cell membrane", "image_url": null},
          {"id": "bio_1_q1_o4", "text": "Ribosome", "image_url": null},
        ],
      },
      {
        "id": "bio_1_q2",
        "order_id": "2",
        "text": "Select organelles found in plant cells.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "bio_1_q2_o1", "text": "Chloroplast", "image_url": null},
          {"id": "bio_1_q2_o2", "text": "Cell wall", "image_url": null},
          {"id": "bio_1_q2_o3", "text": "Centrioles", "image_url": null},
          {"id": "bio_1_q2_o4", "text": "Large vacuole", "image_url": null},
        ],
      },
      {
        "id": "bio_1_q3",
        "order_id": "3",
        "text": "Write one function of mitochondria.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "bio_exam_2",
    "created_at": "2025-02-01",
    "title": "Human Body Systems Quiz",
    "description": "Basic questions about major human body systems.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "bio_2_q1",
        "order_id": "1",
        "text": "Which system is responsible for transporting blood?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "bio_2_q1_o1", "text": "Digestive system", "image_url": null},
          {
            "id": "bio_2_q1_o2",
            "text": "Respiratory system",
            "image_url": null,
          },
          {
            "id": "bio_2_q1_o3",
            "text": "Circulatory system",
            "image_url": null,
          },
          {"id": "bio_2_q1_o4", "text": "Nervous system", "image_url": null},
        ],
      },
      {
        "id": "bio_2_q2",
        "order_id": "2",
        "text": "Select organs of the digestive system.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "bio_2_q2_o1", "text": "Stomach", "image_url": null},
          {"id": "bio_2_q2_o2", "text": "Liver", "image_url": null},
          {"id": "bio_2_q2_o3", "text": "Lung", "image_url": null},
          {"id": "bio_2_q2_o4", "text": "Small intestine", "image_url": null},
        ],
      },
    ],
  },
  {
    "id": "eng_exam_1",
    "created_at": "2025-02-03",
    "title": "English Grammar Test",
    "description": "Grammar basics including parts of speech and sentence use.",
    "has_timer": true,
    "duration_seconds": 1200,
    "questions": [
      {
        "id": "eng_1_q1",
        "order_id": "1",
        "text": "Which word is a verb in the sentence: 'She writes neatly'?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "eng_1_q1_o1", "text": "She", "image_url": null},
          {"id": "eng_1_q1_o2", "text": "writes", "image_url": null},
          {"id": "eng_1_q1_o3", "text": "neatly", "image_url": null},
          {"id": "eng_1_q1_o4", "text": "sentence", "image_url": null},
        ],
      },
      {
        "id": "eng_1_q2",
        "order_id": "2",
        "text": "Select all nouns.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "eng_1_q2_o1", "text": "book", "image_url": null},
          {"id": "eng_1_q2_o2", "text": "run", "image_url": null},
          {"id": "eng_1_q2_o3", "text": "teacher", "image_url": null},
          {"id": "eng_1_q2_o4", "text": "quickly", "image_url": null},
        ],
      },
      {
        "id": "eng_1_q3",
        "order_id": "3",
        "text": "Write one sentence using the word 'beautiful'.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "eng_exam_2",
    "created_at": "2025-02-04",
    "title": "Reading and Vocabulary Quiz",
    "description": "Short vocabulary and comprehension practice.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "eng_2_q1",
        "order_id": "1",
        "text": "What is the synonym of 'happy'?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "eng_2_q1_o1", "text": "sad", "image_url": null},
          {"id": "eng_2_q1_o2", "text": "joyful", "image_url": null},
          {"id": "eng_2_q1_o3", "text": "angry", "image_url": null},
          {"id": "eng_2_q1_o4", "text": "tired", "image_url": null},
        ],
      },
      {
        "id": "eng_2_q2",
        "order_id": "2",
        "text": "Select all words that are adjectives.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "eng_2_q2_o1", "text": "bright", "image_url": null},
          {"id": "eng_2_q2_o2", "text": "table", "image_url": null},
          {"id": "eng_2_q2_o3", "text": "careful", "image_url": null},
          {"id": "eng_2_q2_o4", "text": "running", "image_url": null},
        ],
      },
    ],
  },
  {
    "id": "cs_exam_1",
    "created_at": "2025-02-06",
    "title": "Computer Basics Test",
    "description": "Introductory questions about hardware and software.",
    "has_timer": true,
    "duration_seconds": 1500,
    "questions": [
      {
        "id": "cs_1_q1",
        "order_id": "1",
        "text": "Which of the following is an input device?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "cs_1_q1_o1", "text": "Monitor", "image_url": null},
          {"id": "cs_1_q1_o2", "text": "Keyboard", "image_url": null},
          {"id": "cs_1_q1_o3", "text": "Speaker", "image_url": null},
          {"id": "cs_1_q1_o4", "text": "Printer", "image_url": null},
        ],
      },
      {
        "id": "cs_1_q2",
        "order_id": "2",
        "text": "Select all examples of operating systems.",
        "type": "multi",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "cs_1_q2_o1", "text": "Windows", "image_url": null},
          {"id": "cs_1_q2_o2", "text": "Linux", "image_url": null},
          {"id": "cs_1_q2_o3", "text": "Microsoft Word", "image_url": null},
          {"id": "cs_1_q2_o4", "text": "macOS", "image_url": null},
        ],
      },
      {
        "id": "cs_1_q3",
        "order_id": "3",
        "text": "Write what CPU stands for.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
  {
    "id": "cs_exam_2",
    "created_at": "2025-02-08",
    "title": "Programming Concepts Quiz",
    "description": "Basic programming logic and terminology.",
    "has_timer": false,
    "duration_seconds": null,
    "questions": [
      {
        "id": "cs_2_q1",
        "order_id": "1",
        "text": "Which data type is used for whole numbers?",
        "type": "single",
        "is_mandatory": true,
        "error_text": null,
        "options": [
          {"id": "cs_2_q1_o1", "text": "int", "image_url": null},
          {"id": "cs_2_q1_o2", "text": "bool", "image_url": null},
          {"id": "cs_2_q1_o3", "text": "String", "image_url": null},
          {"id": "cs_2_q1_o4", "text": "double", "image_url": null},
        ],
      },
      {
        "id": "cs_2_q2",
        "order_id": "2",
        "text": "Select all programming languages.",
        "type": "multi",
        "is_mandatory": false,
        "error_text": null,
        "options": [
          {"id": "cs_2_q2_o1", "text": "Dart", "image_url": null},
          {"id": "cs_2_q2_o2", "text": "Python", "image_url": null},
          {"id": "cs_2_q2_o3", "text": "HTML", "image_url": null},
          {"id": "cs_2_q2_o4", "text": "Java", "image_url": null},
        ],
      },
      {
        "id": "cs_2_q3",
        "order_id": "3",
        "text": "Explain what a variable is in programming.",
        "type": "text",
        "is_mandatory": false,
        "error_text": null,
        "options": [],
      },
    ],
  },
]);

var examReportDummyData = ExamReportMapper.fromJsonListToEntityList([
  {
    "id": "exam_1",
    "title": "Biology Mock Test",
    "subject_name": "Biology",
    "created_at": "2026-03-01T10:00:00Z",
    "started_at": "2026-03-01T10:05:00Z",
    "duration_seconds": 1800,
    "submitted_at": "2026-03-01T10:35:00Z",
    "total_marks": 50,
    "obtained_marks": 42,
    "questions": [
      {
        "id": "bio_q1",
        "order_id": "1",
        "text": "What is the powerhouse of the cell?",
        "type": "single",
        "correct_answer": "Mitochondria",
        "submitted_answer": "Mitochondria",
        "obtained_marks": 2,
        "full_marks": 2,
      },
      {
        "id": "bio_q2",
        "order_id": "2",
        "text": "DNA stands for?",
        "type": "text",
        "correct_answer": "Deoxyribonucleic Acid",
        "submitted_answer": "Deoxyribonucleic Acid",
        "obtained_marks": 2,
        "full_marks": 2,
      },
      {
        "id": "bio_q3",
        "order_id": "3",
        "text": "Select plant cell components",
        "type": "single",
        "correct_answer": "Cell wall",
        "submitted_answer": "Cell wall",
        "obtained_marks": 2,
        "full_marks": 2,
      },
    ],
  },

  {
    "id": "exam_2",
    "title": "Physics Mechanics Test",
    "subject_name": "Physics",
    "created_at": "2026-03-02T09:00:00Z",
    "started_at": "2026-03-02T09:02:00Z",
    "duration_seconds": 2700,
    "submitted_at": "2026-03-02T09:45:00Z",
    "total_marks": 60,
    "obtained_marks": 51,
    "questions": [
      {
        "id": "phy_q1",
        "order_id": "1",
        "text": "What is the SI unit of force?",
        "type": "single",
        "correct_answer": "Newton",
        "submitted_answer": "Newton",
        "obtained_marks": 2,
        "full_marks": 2,
      },
      {
        "id": "phy_q2",
        "order_id": "2",
        "text": "State Newton’s Second Law",
        "type": "text",
        "correct_answer": "F = ma",
        "submitted_answer": "Force equals mass times acceleration",
        "obtained_marks": 3,
        "full_marks": 4,
      },
    ],
  },
]);

var dashboardDummyData = DashboardMapper.fromJsonToEntity({
  "summary": {
    "overall_score": 49,
    "attempted_exams": 25,
    "passed_exams": 12,
    "failed_exams": 13,
  },
  "performance_overtime": {
    "range": "weekly",
    "chart_points": [
      {"label": "Sun", "student_score": 22, "average_student_score": 52},
      {"label": "Mon", "student_score": 18, "average_student_score": 24},
      {"label": "Tue", "student_score": 49, "average_student_score": 16},
      {"label": "Wed", "student_score": 38, "average_student_score": 29},
      {"label": "Thu", "student_score": 44, "average_student_score": 43},
      {"label": "Fri", "student_score": 57, "average_student_score": 51},
      {"label": "Sat", "student_score": 41, "average_student_score": 60},
    ],
  },
  "subjectwise_strength": [
    {
      "subject_id": 1,
      "subject_name": "Urology",
      "exam_attempted": 12,
      "average_score": 29,
    },
    {
      "subject_id": 2,
      "subject_name": "Biology",
      "exam_attempted": 18,
      "average_score": 40,
    },
    {
      "subject_id": 3,
      "subject_name": "Psychology",
      "exam_attempted": 10,
      "average_score": 68,
    },
    {
      "subject_id": 4,
      "subject_name": "Physiology",
      "exam_attempted": 14,
      "average_score": 44,
    },
    {
      "subject_id": 5,
      "subject_name": "Anatomy",
      "exam_attempted": 21,
      "average_score": 95,
    },
  ],
});
